### ISSUE TITLE
New User: William Goeller

### ISSUE THREAD

**Issue by KeenWill** [UCLA-VAST-Cluster/user-faq#12]
## Instructions

This issue is used for tracking the progress of setting you up in our cluster. Please follow the instructions below.

1. Please sign up an account on https://id.ucla-vast.com/.
2. Please fill out the required information in [Section 1](#section-1-required-information).
3. Submit this issue for review.
3. The admin will process requests. You don't have to do anything at this moment unless you have questions.
4. The admin will let you know after everything is done by replying to this issue.
5. Please follow [Section 3](#section-3-setup) and finish the checklist carefully.

## Section 1: Required Information

  + Full name: William Goeller
  + Username: keenwill
  + Permanent email: wgoeller@seas.upenn.edu
  + [X]  Description of your project: I am working on a HLS compiler for the OCaml programming language. I will be focusing on compiling pure functions down to hardware and performing automatic hardware parallelization of applicative functors and other functional programming paradigms. My advisor is [Steve Zdancewic](https://www.cis.upenn.edu/~stevez/).
  + [X] Your referrer (if any): Xilinx XACC Program

## Section 2: Process Requests

1. [x] Forward the completed request to a faculty member or the referrer for review.
2. [x] Grant the `cloud` access and add the user to the corresponding group.

The admin will to reply this issue after all above requests are processed.

## Section 3: Setup

1. [x] **Mandatory** Check your account
    + Login to the jump server `cdsc0.cs.ucla.edu` via SSH
    + **Optional**
      + Setup SSH key on the jump server: `ssh-copy-id cdsc0.cs.ucla.edu`.
      + Setup SSH key for your instances: In the user settings on https://cloud.ucla-vast.com/.
    + **Optional** Setup local GUI environment
2. [x] **Mandatory** Read the following Cluster User Guide
    + Do not install Vivado, SDAccel, or Merlin compiler in your home directory or in any of the containers. The following built-in scripts can be executed directly: `xocc`, `v++`, `vivado`, `vivado_hls`, `vitis_hls`.
    + To select the version of Vivado and Vitis (SDAccel), you can `VIV_VER=2021.1 SDA_VER=2021.1 v++`.
    + When you have I/O intensive tasks, please consider using `/tmp`.
3. [x] **Mandatory** Create an instance on https://cloud.ucla-vast.com/
    + Please remember to increase the disk size of the instance.
    + After creating the instance, there might be several minutes of delay for initialization before you can `ssh`.  Please do not stop the instance during the initialization or you would need to recreate the instance.
    + To access your instances, you can `ssh -J cdsc0.cs.ucla.edu <one-of-the-ip-addresses>`.  For SSH config file, you can use `ProxyJump`.
    + For Windows clients, please look the instruction for tunneling.  You can also login to the jump server `cdsc0.cs.ucla.edu` first, then `ssh` from there.
    + The username and password is the same as your credentials.  If you added your SSH key in the user settings, you can access it with your key.
4. [x] **Optional** Comment under this issue if you have any questions
5. [x] **Mandatory** Close this issue when you are all set

**Comment by dotkrnl** [comment]
Hi Will,

Please signup an account on https://id.ucla-vast.com/ and let me know your user name when it is done.  Before we grant your access, please also include a short description of your project, the name of your advisor, and your referrer (if any).

Thank you!  Happy holiday.

Best,
Jason

**Comment by dotkrnl** [comment]
By the way, I have just updated the instructions.

**Comment by KeenWill** [comment]
Hi @dotkrnl, I just updated my initial comment with the information you requested. Let me know if you need anything else!

**Comment by dotkrnl** [comment]
You access is granted.  Please proceed to Section 3.  By the way, my advisor is curious that do you intend to compile directly to RTL code, or to HLS C with pragmas?

**Comment by KeenWill** [comment]
Hi! Thank you for setting this up!

I tried to run `ssh keenwill@cdsc0.cs.ucla.edu` but the operation then times out before even asking me for my password. Do you know why that may be?

And to answer your advisor's question, I will probably compile directly to RTL code (there's a neat [OCaml library](https://github.com/janestreet/hardcaml) that makes writing RTL a bit easier) or I will compile to LLVM and run it through [Xilinx's compiler](https://github.com/Xilinx/HLS). I am still exploring the different options.

**Comment by KeenWill** [comment]
Nevermind! I restarted my computer and now I can ssh in. Not sure what happened there! Thank you for taking the time to set everything up.
